// import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'font-awesome/css/font-awesome.min.css'
import 'Ionicons/dist/css/ionicons.min.css'
// import 'jvectormap/jquery-jvectormap.css'
import 'admlte/css/AdminLTE.min.css'
import 'admlte/css/skins/_all-skins.min.css'

import 'jquery/dist/jquery.min.js'
import 'bootstrap/dist/js/bootstrap.min.js'
// import 'admlte/js/adminlte.min.js'

// import 'fastclick/lib/fastclick.js'
// import 'jquery-sparkline/dist/jquery.sparkline.min.js'
// import 'admlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'
// import 'admlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js'
// import 'jquery-slimscroll/jquery.slimscroll.min.js'
// import 'chart.js/Chart.js'
// import 'admlte/js/pages/dashboard2.js'
// import 'admlte/js/demo.js'
